import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { fonts } from './fonts';
import Header from '@/components/header/header';
import Timer from '@/components/timer/timer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <Providers>
          <Header />
          {children}
          <Timer />
        </Providers>
      </body>
    </html>
  );
}
